const consoles={XR18:{label:"Behringer X18 / XR18",fx:4},MR18:{label:"Midas MR18",fx:4},X32:{label:"Behringer X32 / M32",fx:8},UI24:{label:"Soundcraft Ui24R",fx:4},CQ18:{label:"Allen & Heath CQ18T",fx:4}};
const state={page:"home",lang:"FR",pedals:["Tuner","Overdrive / Distortion","Modulation","Delay","Reverb"],mode:"Live",photo:null};
const $=s=>document.querySelector(s);
function toast(msg){const el=document.createElement("div");el.className="toast";el.textContent=msg;document.body.append(el);setTimeout(()=>el.remove(),2600)}
function render(){document.querySelectorAll("[data-page]").forEach(e=>e.classList.toggle("hidden",e.dataset.page!==state.page));document.querySelectorAll(".navbtn").forEach(e=>e.classList.toggle("active",e.dataset.goto===state.page));renderPedals();renderPatch()}
function renderPedals(){const box=$("#pedals");if(!box)return;box.innerHTML=state.pedals.map((p,i)=>'<div class="pedal"><span class="pill">'+(i+1)+'</span><input value="'+p.replaceAll('"','&quot;')+'" data-pedal="'+i+'"><button class="chip" data-remove="'+i+'">×</button></div>').join("")}
function renderPatch(){const c=$("#console")?$("#console").value:"XR18";const name=$("#channelName")?($("#channelName").value||"Guitare"):"Guitare";const hp=state.mode==="Live"?90:state.mode==="Fidèle"?65:75;const out=$("#patchOutput");if(out)out.innerHTML=`<div class="result"><h3>Patch prêt — ${consoles[c].label}</h3><p><b>Canal :</b> ${name}</p><p><b>Trim :</b> +18 dB recommandé · <b>48V :</b> OFF</p><p><b>HPF :</b> ${hp} Hz · <b>LPF :</b> 18 kHz</p><p><b>EQ :</b> coupe boue 250 Hz, présence +2 dB vers 3 kHz</p><p><b>Dynamics :</b> compression légère 3:1, attaque moyenne</p><p><b>FX :</b> buses disponibles ${consoles[c].fx}</p><p class="muted">Mode ${state.mode} : réglages de départ pédagogiques, à valider à l'écoute.</p></div>`}
function addPedal(){state.pedals.push("Nouvelle pédale");renderPedals()}
function analyse(){renderPatch();state.page="patch";render();toast("Analyse terminée : patch pédagogique généré.")}
function exportPatch(){const c=$("#console").value;const payload={app:"Pedal2Patch",version:"1.0.0",copyright:"© Cédric Carboni - 2026",console:c,channel:$("#channelName").value||"Guitare",mode:state.mode,pedals:state.pedals,phantom:false,generatedAt:new Date().toISOString()};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));a.download="pedal2patch.json";a.click();URL.revokeObjectURL(a.href)}
function regie(){const text="PEDAL2PATCH — FICHE RÉGIE / FOH\nCanal : "+($("#channelName").value||"Guitare")+"\nConsole : "+consoles[$("#console").value].label+"\nChaîne : "+state.pedals.join(" → ")+"\nMode : "+state.mode+"\n48V : OFF\n\nGénéré par Pedal2Patch © Cédric Carboni - 2026";if(navigator.clipboard)navigator.clipboard.writeText(text);toast("Fiche régie copiée.")}
function tap(){const now=performance.now();window.__tap=(window.__tap||[]).slice(-4);if(window.__tap.length){const d=now-window.__tap[window.__tap.length-1];$("#bpm").textContent=Math.round(60000/d)+" BPM"}window.__tap.push(now)}
function power(){const vals=[...document.querySelectorAll("[data-ma]")].map(x=>Number(x.value)||0);$("#maTotal").textContent=vals.reduce((a,b)=>a+b,0)+" mA"}
document.addEventListener("click",e=>{const g=e.target.closest("[data-goto]");if(g){state.page=g.dataset.goto;render()}if(e.target.matches("[data-add]"))addPedal();if(e.target.matches("[data-analyse]"))analyse();if(e.target.matches("[data-export]"))exportPatch();if(e.target.matches("[data-regie]"))regie();if(e.target.matches("[data-tap]"))tap();if(e.target.matches("[data-power]"))power();if(e.target.matches("[data-mode]")){state.mode=e.target.dataset.mode;document.querySelectorAll("[data-mode]").forEach(x=>x.classList.toggle("primary",x===e.target));renderPatch()}if(e.target.matches("[data-demo]")){state.pedals=["Tuner","Tube Screamer","Digital Delay","Plate Reverb"];render();toast("Preset démo chargé.")};if(e.target.matches("[data-lang]")){state.lang=state.lang==="FR"?"EN":"FR";e.target.textContent=state.lang;toast(state.lang==="EN"?"English interface selected":"Interface française sélectionnée")}});document.addEventListener("input",e=>{if(e.target.dataset.pedal!=null)state.pedals[Number(e.target.dataset.pedal)]=e.target.value;if(e.target.id==="console"||e.target.id==="channelName")renderPatch()});window.addEventListener("load",()=>{render();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})});
